spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: 
    password: 
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

weather:
  api:
    url: https://openapi.kpx.or.kr/openapi/
    key: 

server:
  port: 8081

lotto:
  scheduler:
    enabled: false